package com.example.saboresdecasa.enumerates;

public enum TipoTipoProducto {
    MONTADITOS, PLATOSDELMARFRITO, MARISCOSYTAPAS, PLATOSTRADICIONALES, REFESCOS, CERVEZAS, VINOS, LICORES, CAFES, INFUSIONES, POSTRES
}
