package com.example.saboresdecasa.Enumerates;

public enum TipoTipoProducto {
    MONTADITOS, PLATOSDELMARFRITO, MARISCOSYTAPAS, PLATOSTRADICIONALES, REFESCOS, CERVEZAS, VINOS, LICORES, CAFES, INFUSIONES, POSTRES
}
